name: Android

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install node_modules
      run: |
        yarn install --frozen-lockfile
        chmod +x ./android/gradlew

    - name: Build for detox
      run: |
        yarn build:android-release

#    - name: run tests
#      uses: reactivecircus/android-emulator-runner@v2
#      with:
#        api-level: 28
#        avd-name: Pixel_API_28
#        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
#        script: yarn test:android-release

    - name: Android Emulator
      timeout-minutes: 10
      continue-on-error: true
      run: |
        echo "Starting emulator"
        nohup $ANDROID_HOME/emulator/emulator -avd Pixel_API_28 -no-audio -no-snapshot -no-window -gpu swiftshader_indirect -no-boot-anim &
        $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
        $ANDROID_HOME/platform-tools/adb devices
        echo "Emulator started"

    - name: Android Detox
      run: yarn test:android-release
